'use strict';

// copied from Excel file (code generated via Formulas)

const MANUAL_DATA = [];
MANUAL_DATA.push({item: 'PV_Multi_Function_Relay', sitemap:'Status'});
MANUAL_DATA.push({item: 'PV_Device_SN', sitemap: 'Infos'});
MANUAL_DATA.push({item: 'PV_Device_Model_Info', sitemap: 'Infos'});
MANUAL_DATA.push({item: 'PV_Firmware_Version', sitemap: 'Infos'});
MANUAL_DATA.push({item: 'PV_DateTime', sitemap: 'Infos'});
MANUAL_DATA.push({item: 'PV_Fault_1_0', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_1_1', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_1_2', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_1_3', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_1_4', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_1_5', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_1_6', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_1_7', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_1_8', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_2_1', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_2_2', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_2_3', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_2_4', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_2_5', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_2_6', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_2_7', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_3_0', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_3_1', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_3_2', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_3_3', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_3_4', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_3_5', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_3_6', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_3_7', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_3_8', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_3_9', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_3_10', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_ARM_0', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_ARM_1', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Fault_ARM_2', sitemap: 'Status'});
MANUAL_DATA.push({item: 'PV_Period_1_Enabled', sitemap: 'Period 1'});
MANUAL_DATA.push({item: 'PV_Period_2_Enabled', sitemap: 'Period 2'});
MANUAL_DATA.push({item: 'PV_Period_3_Enabled', sitemap: 'Period 3'});
MANUAL_DATA.push({item: 'PV_Period_4_Enabled', sitemap: 'Period 4'});
MANUAL_DATA.push({item: 'PV_Period_5_Enabled', sitemap: 'Period 5'});
MANUAL_DATA.push({item: 'PV_Period_6_Enabled', sitemap: 'Period 6'});
MANUAL_DATA.push({item: 'PV_Period_1_Start_H', sitemap: 'Period 1'});
MANUAL_DATA.push({item: 'PV_Period_2_Start_H', sitemap: 'Period 2'});
MANUAL_DATA.push({item: 'PV_Period_3_Start_H', sitemap: 'Period 3'});
MANUAL_DATA.push({item: 'PV_Period_4_Start_H', sitemap: 'Period 4'});
MANUAL_DATA.push({item: 'PV_Period_5_Start_H', sitemap: 'Period 5'});
MANUAL_DATA.push({item: 'PV_Period_6_Start_H', sitemap: 'Period 6'});
MANUAL_DATA.push({item: 'PV_Period_1_Start_M', sitemap: 'Period 1'});
MANUAL_DATA.push({item: 'PV_Period_2_Start_M', sitemap: 'Period 2'});
MANUAL_DATA.push({item: 'PV_Period_3_Start_M', sitemap: 'Period 3'});
MANUAL_DATA.push({item: 'PV_Period_4_Start_M', sitemap: 'Period 4'});
MANUAL_DATA.push({item: 'PV_Period_5_Start_M', sitemap: 'Period 5'});
MANUAL_DATA.push({item: 'PV_Period_6_Start_M', sitemap: 'Period 6'});
MANUAL_DATA.push({item: 'PV_Period_1_Stop_H', sitemap: 'Period 1'});
MANUAL_DATA.push({item: 'PV_Period_2_Stop_H', sitemap: 'Period 2'});
MANUAL_DATA.push({item: 'PV_Period_3_Stop_H', sitemap: 'Period 3'});
MANUAL_DATA.push({item: 'PV_Period_4_Stop_H', sitemap: 'Period 4'});
MANUAL_DATA.push({item: 'PV_Period_5_Stop_H', sitemap: 'Period 5'});
MANUAL_DATA.push({item: 'PV_Period_6_Stop_H', sitemap: 'Period 6'});
MANUAL_DATA.push({item: 'PV_Period_1_Stop_M', sitemap: 'Period 1'});
MANUAL_DATA.push({item: 'PV_Period_2_Stop_M', sitemap: 'Period 2'});
MANUAL_DATA.push({item: 'PV_Period_3_Stop_M', sitemap: 'Period 3'});
MANUAL_DATA.push({item: 'PV_Period_4_Stop_M', sitemap: 'Period 4'});
MANUAL_DATA.push({item: 'PV_Period_5_Stop_M', sitemap: 'Period 5'});
MANUAL_DATA.push({item: 'PV_Period_6_Stop_M', sitemap: 'Period 6'});

module.exports.MANUAL_DATA = MANUAL_DATA;
